############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

# [[main]]
# name = "Contact Us"
# url = "contact/"
# weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

# [[main]]
# weight = 4
# name = "Legal"
# hasChildren = true

# [[main]]
# parent = "Legal"
# name = "Privacy Policy"
# url = "privacy-policy/"

# [[main]]
# parent = "Legal"
# name = "Terms & Conditions"
# url = "terms-and-conditions/"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "contact/"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "authors/"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "categories/"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "404/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
